services:

  selfservice-postgre:
    container_name: selfservice_db
    image: postgres
    environment:
      POSTGRES_DB: selfservice
      POSTGRES_USER: theworldwar
      POSTGRES_PASSWORD: helloworld
      PGDATA: /data/postgres
    volumes:
      - ./postgres-selfservice:/data/postgres
    ports:
      - "5433:5432"
    restart: always
